# ============================================================================
# GitHub Sponsors 및 후원 설정 파일
#
# 목적:
# - 저장소 우측 사이드바에 "Sponsor" 버튼 표시
# - 여러 후원 플랫폼 링크를 한 곳에 모아서 관리
# - 오픈소스 프로젝트 유지를 위한 재정 지원 유도
#
# 표시 위치:
# - GitHub 저장소 메인 페이지 우측 상단 "Sponsor" 버튼
# - README 아래 자동으로 후원 옵션 표시
#
# 사용 가이드:
# 1. 사용하는 플랫폼만 활성화 (주석 제거)
# 2. 사용하지 않는 플랫폼은 주석 처리하거나 삭제
# 3. 개인 프로젝트에서 후원 안 받으면 이 파일 전체 삭제
#
# 공식 문서:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# ============================================================================

# ===========================================================================
# GitHub Sponsors (권장)
#
# 설명:
# - GitHub에 직접 통합된 후원 플랫폼
# - GitHub 계정으로 바로 후원 가능
# - 수수료가 없거나 낮음
# - 개인 계정 또는 조직 계정 지정 가능
#
# 사용법:
# - github: username (단일 계정)
# - github: [user1, user2, org1] (여러 계정, 최대 4개)
#
# GitHub Sponsors 설정:
# 1. https://github.com/sponsors 방문
# 2. "Join the waitlist" 또는 "Set up sponsorship" 클릭
# 3. 프로필, 티어, 결제 정보 설정
# 4. 여기에 username 입력
# ===========================================================================
# github: buenhyden
# custom: ["https://buymeacoffee.com/yourname"]

# ============================================================================
# 권장 설정 (시작하기)
# ============================================================================
#
# 개인 개발자:
# 1. GitHub Sponsors (가장 통합도 높음)
# 2. Ko-fi (간단하고 빠름)
# 3. Custom URL (PayPal 등)
#
# 오픈소스 프로젝트:
# 1. Open Collective (투명성)
# 2. GitHub Sponsors
# 3. Tidelift (기업 후원)
#
# 조직:
# 1. GitHub Sponsors (조직 계정)
# 2. Open Collective
# 3. LFX Crowdfunding (대형 프로젝트)
#
# ============================================================================
# 플랫폼별 비교
# ============================================================================
#
# | 플랫폼 | 수수료 | 장점 | 단점 |
# |--------|--------|------|------|
# | GitHub Sponsors | 0% (처음 1년) | 통합도 | 지역 제한 |
# | Patreon | 5-12% | 티어 관리 | 수수료 높음 |
# | Open Collective | 10% | 투명성 | 설정 복잡 |
# | Ko-fi | 0% (Premium 월 $6) | 간단함 | 기능 제한 |
# | Tidelift | varies | 기업 후원 | 진입장벽 |
#
# ============================================================================
# 사용 팁
# ============================================================================
#
# 1. 너무 많은 옵션 제공 금지: 2-3개 플랫폼만 선택
# 2. 주력 플랫폼 먼저 나열: GitHub Sponsors 또는 Open Collective 먼저
# 3. 후원 용도 명시: README나 별도 페이지에서 후원금 사용처 설명
# 4. 갱신: 플랫폼 변경 시 이 파일도 업데이트
# 5. 테스트: 저장소에서 "Sponsor" 버튼이 제대로 보이는지 확인
#
# ============================================================================
