# ============================================================================
# Labeler 설정 (Labeler Configuration)
#
# 목적 (Purpose):
# - PR의 변경된 파일에 따라 자동 라벨 추가 (Auto-label PRs based on changed files)
#
# [CUSTOMIZE] 프로젝트 구조에 맞게 수정하세요. (Customize for your project structure.)
# ============================================================================

# Studies
"studies":
  - "Studies/**/*"

# TIL
"til":
  - "TIL/**/*"

# References
"references":
  - "References/**/*"

# Agent & Rules
"agent":
  - ".agent/**/*"
  - "agent/**/*"

# Infrastructure
"infra":
  - "infra/**/*"

# CI/CD
"ci/cd":
  - ".github/**/*"
