documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "**/*.md"

ci-cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"
      - any-glob-to-any-file: "pyproject.toml"
      - any-glob-to-any-file: "uv.lock"

research:
  - changed-files:
      - any-glob-to-any-file: "References/**"
      - any-glob-to-any-file: "TIL/**"

agent-rules:
  - changed-files:
      - any-glob-to-any-file: ".agent/**"
