name: Reproducible Python Data Analysis
description: >
  Turn an ad hoc Python or notebook-based analysis into a fully reproducible,
  path-agnostic workflow.

triggers:
  - user_request: "make this analysis reproducible"
  - user_request: "clean up this notebook"
  - user_request: "prepare this project for sharing"

assumptions:
  - The user has one or more notebooks or scripts containing analysis logic.    

steps:
  - name: Inventory notebooks and scripts
    action: analyze_repository
    description: >
      Identify notebooks and scripts involved in the analysis and detect any
      absolute paths or environment-specific assumptions. 

  - name: Extract reusable code
    action: refactor_code
    description: >
      Move reusable functions and classes into src/ modules and adjust
      notebooks/scripts to import from src/ instead of duplicating logic.

  - name: Normalize paths
    action: modify_files
    description: >
      Replace absolute paths with project-root–relative or configuration-based
      paths across notebooks and scripts, using a clear base directory strategy.
      

  - name: Define environment
    action: modify_files
    description: >
      Create or update environment specification (requirements.txt,
      environment.yml, or pyproject.toml) containing all required packages for
      the analysis. 

  - name: Create scripted entrypoint
    action: modify_files
    description: >
      Add a script (for example, src/run_analysis.py) that reproduces the
      analysis end-to-end using configuration and relative paths, without manual
      notebook interaction. 

  - name: Update documentation
    action: summarize
    description: >
      Update the README or add a docs/analysis.md file to describe:
        - How to set up the environment.
        - How to run the analysis script.
        - How to re-run or adapt notebooks using the structured project layout.
